name: Build All Apps
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Перечислите здесь названия папок ваших 4 проектов
        project_path: [adiabatic, atwood, physics, stokes]
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Sync
        run: |
          cd ${{ matrix.project_path }}
          npm install
          npx cap sync android

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build APK
        run: |
          cd ${{ matrix.project_path }}/android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.project_path }}-debug.apk
          path: ${{ matrix.project_path }}/android/app/build/outputs/apk/debug/app-debug.apk